apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  # not related to selector labels for pods
  labels:
    app: fluentd
# daemonset spec
spec:
  # labels to look out in pods (AND operator)
  selector:
    matchLabels:
      app: fluentd
  # pod template spec
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      nodeSelector:
        foo: bar
      containers:
        - name: fluentd
          image: fluent/fluentd:v0.14.10
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers