apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
# pod spec
spec:
  volumes:
    - name: tls-certs
      secret:
        # name of the secret
        secretName: kuard-tls
  containers:
    - name: kuard-tls
      image: "gcr.io/kuar-demo/kuard-amd64:blue"
      imagePullPolicy: Always
      volumeMounts:
        # mounting the secret as a set of files
        - name: tls-certs
          # tls path used by pod to support TLS, /tls/kuard.crt, /tls/kuard.key
          mountPath: /tls
          readOnly: true
