apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpaca-prod
  template:
    metadata:
      labels:
        app: alpaca-prod
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:green
          imagePullPolicy: IfNotPresent
          name: kuard-amd64
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP