---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-and-services
rules:
  - apiGroups: [""] # core group
    resources: ["pods", "services"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-and-services
# role to bind (authorization)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-and-services
# identity to allow (authentication) using any authentication provider
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: alice
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: mydevs
