apiVersion: v1
kind: Pod
metadata:
  # name of pod
  name: kuard
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      # name of container
      name: kuard
      # port to publish
      ports:
        - containerPort: 8080
          # name of port
          name: http
          protocol: TCP
      # app specific health check
      livenessProbe:
        # health check via http GET method
        httpGet:
          # path should exist in app
          path: /healthy
          # app should be listening on this port, port name from above
          port: http
        # wait for 5 seconds, before probing
        initialDelaySeconds: 5
        # max time to wait for response, statusCodeSuccess[200,400)
        timeoutSeconds: 1
        # probe every 10 seconds
        periodSeconds: 10
        # after consecutive health failures, apply restartPolicy of Pod
        failureThreshold: 3
        # successThreshold defaults to 1